services:

  strawberry_demo:
    build:
      context: ./docker
    image: strawberry_django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./code/:/code
    ports:
      - 8000:8000
    networks:
      - lab_network

  # my_db:
  #   image: postgres
  #   environment:
  #     - 'POSTGRES_USER=postgres'
  #     - 'POSTGRES_PASSWORD=secret123'
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - lab_network

# volumes:
#   pgdata:

networks:
  lab_network:
    external: false
