# Generated by Django 5.1.3 on 2024-11-21 14:04

import django.db.models.deletion
import django_choices_field.fields
import strawberry_demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The color name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the fruit variety', max_length=20)),
                ('category', django_choices_field.fields.TextChoicesField(choices=[('citrus', 'Citrus'), ('berry', 'Berry')], choices_enum=strawberry_demo.models.FruitCategory, help_text='The category of the fruit', max_length=6)),
                ('color', models.ForeignKey(blank=True, help_text='The color of this kind of fruit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='strawberry_demo.color')),
            ],
        ),
    ]
